before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: hmiW66p/6dobhM+EkW/UmrhnyLeEWgNYEzRk25i68mlWZUMpCPLrt4xqrPoi159qyYShugHrXHcjuT5avTLF2ddM2eVUlT2qFYQ27dtM76bilO6E2fBHDfHsdxXoY20geZyQewu5uLVhtkTUHX3o6LAzmojsIDDNXd5gDUKxKbKE+I//objcwQf80MtFfK7QF5ay4rW1VajBtjlnyzfRGHmyXTU/DQRP9Ks3afy8r+wr9stkoMREi4ApZ0f/rHxLdhzrdl+vxvfXgSTwiziX6XBP88dvAtOxl3HNZlZNW5e9niaP+xWBYFGM0po83yNxK0P523lFTNTrhEbAlI4hITkIbPETyixVV8raf03RhgY7e5QAYjophAyVZ74sizUrQfuxJlOgQTBnYr6DL3m1j/MDi2rWYctIhkRAeYakE0mEwjEBznJ21MccI+H3wDH24DxMBhogBF8X9vXfTImbmvI4iSh+RhIsLOztn6oxgQF+t6VRZf1rrF7YjZGQKcm1+ozwwKDWKoU9COY7Nwe61Ai74AwFumA2mZLU4Z8kBCgPNPzgPlSgRVXIbjBb18sD1lTpWOAItHkv91iFTka2VnjBEjTUARkod5Faz04HTtJIP93UkeuJPK8UuWpy1UIC7wfEWfxU0ZPk/3hUX19qsJW6OPtWpGmodSfK2Sm3r6U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
